import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { IconCopyright, IconHome } from '@tabler/icons-react';
import Link from 'next/link';
import React from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-2 sm:p-8 pb-20 min-h-svh font-[family-name:var(--font-geist-sans)] flex justify-between items-center flex-col">
          <main className="flex pb-20 items-center justify-center w-full lg:w-[calc(1024px - 2rem)]">
            {children}
          </main>
          <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center text-sm">
            <Link className="flex items-center" href="/">
              <IconHome size={16} className="mr-1" /> Home
            </Link>
            <p className="flex items-center">
              <IconCopyright className="mr-1" size={16} />{' '}
              <span>{new Date().getFullYear()} puzzlefactory productions</span>
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
